# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/magic_sql.ipynb.

# %% auto 0
__all__ = []

# %% ../nbs/magic_sql.ipynb 3
from .core import SQL_ENGINE
import os
os.environ['DATABASE_URL']=SQL_ENGINE.replace("+psycopg2", "")
